### ISSUE TITLE
[Bug] Opening actor sheet turns inner ring black

### ISSUE THREAD

**Issue by lholden** [ChasarooniZ/PF2e-Reactive-Token-Ring#23]
**Describe the bug**
On Pathfinder 2e, opening an actor sheet and then closing it turns the inner ring black.

To make sure this wasn't a weird mod interaction I can confirm this is still a problem with just this mod, the Token Pack, and Tokenizer installed in a fresh world.

I'm on Foundry v12 328, PF 6.0.4, REDY 1.1.6. The settings for REDY are entirely default.

Changing the ring color to something specific doesn't seem to help. It will still go black. Opening the sheet again flashes the color that was set before going back to black again.

**To Reproduce**
1. Drag actor to scene
2. Double click token to open sheet
3. Close sheet

**Expected behavior**
It should retain the ring color it had before opening the sheet.

**Screenshots**
![image](https://github.com/user-attachments/assets/ae8cdcc5-b9fe-459b-b176-53c23a70fb37)
![image](https://github.com/user-attachments/assets/df9f3b03-fd51-4c04-9cbe-d67c6e39fb5f)

**Comment by lholden** [comment]
After some fiddling around. I've noticed that turning "Scale Damage/Heal Duration" *off* prevents the ring from turning black. However, when you close the sheet the ring flashes green as if you had healed them.

**Comment by ChasarooniZ** [comment]
Ah thank you I noticed black ring issues too I'll look into it
