### ISSUE TITLE
[Bug] Color ring changes from default after flashing (PF2E)

### ISSUE THREAD

**Issue by lholden** [ChasarooniZ/PF2e-Reactive-Token-Ring#25]
**Describe the bug**
Using PF2E and the new Bronze token ring. When no color is set for a token, and you target a token to make it flash, it then ends up with the wrong color. 

**To Reproduce**
1. Swap to the "Foundry VTT Bronze Ring" token rings in the Core settings. 
2. See that it has a red color (like with REDY disabled)
3. Target (or otherwise flash) the token
4. See that it is now blue
5. Open the settings for a token and it changes back to red.

**Expected behavior**
It's red after flashing. (Or whatever else the default color is for that token ring) :)

**Screenshots**
![image](https://github.com/user-attachments/assets/77531ca6-1e7b-443a-acf8-18635429badd)
![image](https://github.com/user-attachments/assets/4f83189a-c6ee-4659-9a08-ac5cb405eac9)

**Comment by ChasarooniZ** [comment]
I'll look into it, but maybe a system bug? I just use the system built in `Flash Token` feature

**Comment by lholden** [comment]
Ahha! You know, this does look like a bug with Foundry!

I just launched a new world on the D&D system and swapped to the bronze token and got the same result!

And you are welcome! :D

**Comment by lholden** [comment]
https://github.com/foundryvtt/foundryvtt/issues/11487
