### ISSUE TITLE
[Bug] lang/es.json does not exist

### ISSUE THREAD

**Issue by farling42** [ChasarooniZ/PF2e-Reactive-Token-Ring#27]
**Describe the bug**
Error reported on trying to install latest update.
![image](https://github.com/user-attachments/assets/deb06fd9-7729-4fe5-976b-5f69d45c98e5)

It is because module.json references "lang/" path instead of "languages/" path for some files.

**Comment by ChasarooniZ** [comment]
Aware of issue, pushing fix
