### ISSUE TITLE
[Feature] Dynamic frames for PC/Friendly NPC/Enemy NPC

### ISSUE THREAD

**Issue by weihanderz** [ChasarooniZ/PF2e-Reactive-Token-Ring#51]
**Is your feature request related to a problem? Please describe.**
Players usually use frames to quickly distinguish between types of tokens, such as player characters, friendly NPCs and enemy NPCs. It would be nice to have dynamic frames have different set of frames between each of these.

**Describe the solution you'd like**
Have a setting for frames depending on which type of token

**Comment by weihanderz** [comment]
As an extra, it would be really dramatic if the dynamic tokens could fade into another, for example, when a friendly NPC frame faded into an enemy NPC frame.

**Comment by ChasarooniZ** [comment]
Sorry going to need more details.

Atm there is an option to configure the frames **color** for each of those options. However, there is no way to set multiple dynamic frames at once (IE one for some tokens, some for other tokens)

**Comment by ChasarooniZ** [comment]
for later me as a ring type possible [color filters](https://brinzaengineering.weebly.com/seeing-and-light)

**Comment by weihanderz** [comment]
> Sorry going to need more details.
> 
> Atm there is an option to configure the frames **color** for each of those options. However, there is no way to set multiple dynamic frames at once (IE one for some tokens, some for other tokens)
Ah, I see. It would be nice for the future to be able to set some dynamic frames for one token type and others for other types. That's all :) Thank you

**Comment by ChasarooniZ** [comment]
Oh, yeah that's a FOUNDRY limitation not a me thing
